#!/bin/bash
echo -e "Nmap Find Hosts on IP Scan"
echo ""
sleep 1

echo -e "Enter URL [e.g. nmap.org] "
read url
echo ""

echo -e "Running [nmap -p 80 --script hostmap-bfk.nse $url].."
echo ""
sleep 1

nmap -p 80 --script hostmap-bfk.nse $url

