#!/bin/bash



echo -e "Nmap HTTP Recon Scan"
echo ""
sleep 1

echo -e "Enter IP [e.g. 198.168.10.55] "
read ip
echo ""

echo -e "Additional option - Would you like to specify a base path? [y,n] "
read basePath
echo ""

verbosity_default="Y"
read -p "Additional option - Would you like to add verbosity [$verbosity_default,n] " verbosity_default 
verbosity=${verbosity:-$verbosity_default}

if ([[ $basePath = "Y" || $basePath = "y" ]] && [[ $verbosity = "y" || $verosity = "$verbosity_default" ]]) ; then

  basePathOption_default="pub"
  read -p "Enter base path: [default $basePathOption_default] " basePathOption_default
  basePath_option=${basePath_option:-$basePathOption_default}
  echo ""
  
  echo -e "Running [nmap --script http-enum --script-args http-enum.basepath=$basePath_option $ip -v].."
  echo ""
  sleep 1

  nmap --script http-enum --script-args http-enum.basepath=$basePath_option $ip -v

fi

if ([[ $basePath = "N" || $basePath = "n" ]] && [[ $verbosity = "y" || $verbosity = "$verbosity_default" ]]) ; then

  echo -e "Running [nmap --script http-enum $ip -v].."
  echo ""
  sleep 1

  nmap --script http-enum $ip -v

fi

if ([[ $basePath = "Y" || $basePath = "y" ]] && [[ $verbosity = "N" || $verbosity = "n" ]]) ; then

  basePathOption_default="pub"
  read -p "Enter base path: [default $basePathOption_default] " basePathOption_default
  basePath_option=${basePath_option:-$basePathOption_default}
  echo ""

  echo -e "Running [nmap --script http-enum --script-args http-enum.basepath=$basePath_option $ip].."
  echo ""
  sleep 1

  nmap --script http-enum --script-args http-enum.basepath=$basePath_option $ip

fi

