#!/bin/bash
clear
#Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $BLUE"#                                 ||"$ENDCOLOR;
echo -e $BLUE"#                                 ||_________________________/'|"$ENDCOLOR;
echo -e $BLUE"#                               _| O======/                    |"$ENDCOLOR;
echo -e $BLUE"#                              |_|               ============  |"$ENDCOLOR;
echo -e $BLUE"#                                |  __   ______________________|"$ENDCOLOR;
echo -e $BLUE"#                                |_/  )  (    |___||     O-   /"$ENDCOLOR;
echo -e $BLUE"#  C a r p e   O m n i o u s          (  )    /  / |_________/"$ENDCOLOR;
echo -e $BLUE"#                                     (  )   /  /    | ) |   |"$ENDCOLOR;
echo -e $BLUE"#                                     (__)  /  /     \___|__("$ENDCOLOR;
echo -e $BLUE"#                                          /  /          )   \ "$ENDCOLOR;
echo -e $BLUE"#                                         /  /            )   \ "$ENDCOLOR;
echo -e $BLUE"#                                        /  /              )___\ "$ENDCOLOR;
echo -e $BLUE"#                                       /  / "$ENDCOLOR;
echo -e $BLUE"#                                      /__/"$ENDCOLOR;
echo -e $BLUE"#                                "$ENDCOLOR;
echo ""
echo -e $YELLOW"Thank you for choosing SolidOptionOS!"$ENDCOLOR;
echo ""
echo -e $YELLOW"This script will setup and run OpenVPN as a service/daemon."$ENDCOLOR;
echo -e $YELLOW"You must be root to use the script.  Logging in as root.."$ENDCOLOR;
echo ""
sudo su
echo ""
echo -e $YELLOW"Installing openvpn.."$ENDCOLOR;
echo ""
sudo apt-get install openvpn -y
echo -e $GREEN"Done."$ENDCOLOR;
echo ""
echo ""
echo -e $YELLOW"Copying .ovpn files to /etc/openvpn.."$ENDCOLOR; 
echo ""
sudo cp ivpn-openvpn-config/* /etc/openvpn/
echo -e $GREEN"Done."$ENDCOLOR;
echo ""
savepass_default="Y"
read -p "Would you like to save your username/password in a text file? [$savepass_default,n] " savepass_default
savepass=${savepass:-$savepass_default}

if [[ $savepass = "savepass_default" || $savepass = "y" ]] ; then

  sudo touch /etc/openvpn/pass
  echo -e $YELLOW"Enter your IVPN username: [starts with 'ivpn'] "$ENDCOLOR;
  read ivpnusername
  echo ""
  echo -e $YELLOW"You have entered $ivpnusername."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"Enter your IVPN password: "$ENDCOLOR;
  read ivpnpass
  echo ""
  echo -e $YELLOW"You have entered $ivpnpass."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"Updating /etc/openvpn/pass.."$ENDCOLOR;
  echo ""
  sudo echo "$ivpnusername" >> /etc/openvpn/pass
  sudo echo "$ivpnpass" >> /etc/openvpn/pass
  echo -e $GREEN"Done."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"Updating .ovpn files in /etc/openvpn.."$ENDCOLOR;
  echo ""
  sudo sed -i 's/auth\-user\-pass/auth\-user\-pass\ pass/g' /etc/openvpn/*.ovpn
  echo -e $GREEN"Done."$ENDCOLOR;
  
else

  echo -e $YELLOW"Okay. Maybe later."$ENDCOLOR;
  echo ""

fi

startvpn_default="Y"
read -p "Start OpenVPN service now? [$startvpn_default,n] " startvpn_default
startvpn=${startvpn:-$startvpn_default}

if [[ $startvpn = "startvpn_default" || $startvpn = "y" ]] ; then

  echo -e $YELLOW"Starting openvpn service.."$ENDCOLOR;
  echo ""
  sudo service openvpn start
  echo ""
  echo -e $YELLOW"Checking to see if OpenVPN tunnel has started.."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"If you see a 'tun' device created (normally tun0) then you have successfully configured OpenVPN."$ENDCOLOR;
  ip addr
  echo ""
  echo -e $YELLOW"Checking your external IP to verify connection.."$ENDCOLOR;
  echo ""
  curl ifconfig.co
  echo ""
  echo -e $GREEN"Done. Goodbye."$ENDCOLOR;

else

  echo -e $YELLOW"Okay.  You can start OpenVPN from the command line with 'sudo service openvpn start'."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"You can check that the OpenVPN tunnel has been successfully created by looking at the output of 'ip addr'."$ENDCOLOR;
  echo ""
  echo -e $YELLOW"You can check your external IP to verify that you are connected with 'curl ifconfig.co'."$ENDCOLOR;
  echo ""
  echo -e $GREEN"Goodbye."$ENDCOLOR;

fi  



#HEIGHT=15
#WIDTH=40
#CHOICE_HEIGHT=4
#BACKTITLE="OpenVPN Server Selection"
#TITLE="IVPN Servers"
#MENU="Choose one of the following servers:"
#
#OPTIONS=(1 "Canada"
#         2 "France"
#	 3 "Germany"
#	 4 "Hong Kong"
#	 5 "Icoland"
#	 6 "Italy"
#	 7 "Netherlands"
#	 8 "Romania"
#	 9 "Sweden"
#	 10 "Switzerland"
#	 11 "United Kingdom"
#	 12 "USA - Atlanta"
#	 13 "USA - Dallas"
#	 14 "USA - Los Angeles"
#	 15 "USA - Miami"
#	 16 "USA - New Jersey"
#	 17 "USA - Salt Lake City")
#
#CHOICE=$(dialog --clear \
#	--backtitle "$BACKTITLE" \
#	--title "$TITLE" \
#	--menu "$MENU" \
#	$HEIGHT $WIDTH $CHOICE_HEIGHT \
#	"${OPTIONS[@]}" \
#	2>&1 >/dev/tty)
#
#clear
#case $CHOICE in
#	1)
#		echo "You chose Canada"
#		;;
#	2)
#		echo "You chose France"
#		;;
#	3)
#                echo "You chose Germany"
#		;;		
#	4)
#		echo "You chose Hong Kong"
#		;;
#	5)
#		echo "You chose Icoland"
#		;;
#	6)
#		echo "You chose Italy"
#		;;
#	7)
#		echo "You chose Netherlands"
#		;;
#	8)
#		echo "You chose Romania"
#		;;
#	9)
#		echo "You chose Sweden"
#		;;
#	10)	
#		echo "You chose Switzerland"
#		;;
#	11)	
#		echo "You chose United Kingdom"
#		;;
#	12)	
#		echo "You chose USA - Atlanta"
#		;;
#	13)	
#		echo "You chose USA - Dallas"
#		;;
#	14)	
#		echo "You chose USA - Los Angeles"
#		;;
#	15)	
#		echo "You chose USA - Miami"
#		;;
#	16)	
#		echo "You chose USA - New Jersey"
#		;;
#	17)	
#		echo "You chose USA - Salt Lake City"
#		;;
#esac

#/usr/bin/openvpn --config ivpn-openvpn-config/$vpnServer
