#!/bin/bash
clear
#Colors

dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"SolidOptionOS Solid Scan"$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo ""
echo -e $BLUE"Checking for root..."$ENDCOLOR;
sleep 0.5
if [ $USER != root ]; then
echo -e $RED"Sorry, you must run this from as root."$ENDCOLOR
echo -e $YELLOW"Exiting..."$ENDCOLOR
exit 0
fi
echo -e $BLUE"Installing clamav first..."$ENDCOLOR;
sleep 1
apt-get install clamav -y
echo ""
echo -e $BLUE"Updating with freshclam..."$ENDCOLOR;
sleep 1
freshclam
echo ""
#echo -e $BLUE"Creating temp directories.."$ENDCOLOR;
#sleep 1
#mkdir /tmp/clamscan
#mkdir /var/log/clamscan
#mkdir /clamav-quarentine
echo ""
echo -e $BLUE"Ok. Let's scan."$ENDCOLOR;
sleep 0.5
echo -e $YELLOW"Default options are '-r ~/ -i --tempdir=/tmp/clamscan --log=/var/log/clamscan/log --copy=/clamav-quarentine/' Use? {y/n} "$ENDCOLOR
read OPTIONS
if [[ $OPTIONS = 'y' || $OPTIONS = 'Y' ]] ; then
clamscan -r ~/ -i --tempdir=/tmp/clamscan --log=/var/log/clamscan/log --copy=/clamav-quarentine/
sleep 1
echo ""
echo ""
echo -e $RED"###############################################"$ENDCOLOR
echo -e $BLUE"#               Scan Complete.                #"$ENDCOLOR
echo -e $RED"###############################################"$ENDCOLOR
echo ""
echo -e $YELLOW"Have A Solid Day"$ENDCOLOR;
echo ""
exit
else
echo -e $YELLOW"Enter new options: "$ENDCOLOR
read CUSTOPTS
sleep 1
clamscan $CUSTOPTS
sleep 1
echo ""
echo ""
echo -e $RED"###############################################"$ENDCOLOR
echo -e $BLUE"#               Scan Complete.                #"$ENDCOLOR
echo -e $RED"###############################################"$ENDCOLOR
echo ""
echo -e $YELLOW"Have A Solid Day"$ENDCOLOR;
echo ""
exit
fi
