#!/bin/bash
echo -e "Nmap SMB-Brute Scan"
echo ""
sleep 1

echo -e "Enter IP [e.g. 192.168.1.101] "
read ip
echo ""

echo -e "Running [nmap -sV -p  --script smb-brute $ip].."
echo ""
sleep 1

nmap -sV -p 445 --script smb-brute $ip

