#!/bin/bash
echo -e "Nmap HTTP Title Scan"
echo ""
sleep 1

echo -e "Enter IP [e.g. 192.168.1.0/24] "
read ip
echo ""

verbosity_default="Y"
read -p "Would you like to add verbosity? [$verbosity_default,n] " verbosity_default
verbosity=${verbosity:-$verbosity_default}
echo ""

if [[ $verbosity = "y" || $verbosity = "$verbosity_default" ]] ; then
 
  echo -e "Running [name --script http-title -sV -p 80 $ip -v].."
  echo ""
  sleep 1
  
  nmap --script http-title -sV -p 80 $ip -v

else

  echo -e "Running [nmap --script http-title -sV -p 80 $ip].."
  echo ""
  sleep 1

  nmap --script http-title -sV -p 80 $ip

fi
