#!/bin/bash
echo -e "Nmap DNS Brute Force Scan"
echo ""

echo -e "Enter URL to scan: [e.g. vulnweb.com] "
read url

echo ""
echo -e "Running [nmap -p 80 --script dns-brute.nse $url].."
echo ""
sleep 1

nmap -p 80 --script dns-brute.nse $url
