#!/bin/bash
echo -e "Nmap Traceroute Geolocation Scan"
echo ""
sleep 1

echo -e "Enter URL [hackertarget.com] "
read url
echo ""

echo -e "Running [nmap --traceroute --script traceroute-geolocation.nse -p 80 $url].."
echo ""
sleep 1

nmap --traceroute --script traceroute-geolocation.nse -p 80 $url

