#!/bin/bash
clear

## Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

## Paths
PERSISTENCEPATH="/"
SCRIPTSPATH="/home/h3x/optionZ3ro"
CAPTUREPATH="/captures"

## Preferred Options
SETOPTIONS=" --showack --band abg --wps -aMU --cswitch 1"

## Date
### mm/dd/yyyy ####
now="$(date +'%d.%m.%Y')"

echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"# Created by h3x at SolidOptionOS.  All rights reserved. 2015   #"$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;

echo ""
echo -e $BLUE"Creating a captures and captures/hs folder in / "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo mkdir -p /captures/hs]"$ENDCOLOR;
echo ""
mkdir -p /captures/hs
echo ""
echo -e $BLUE"Next, let's prepare our interface. "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo ifconfig]"$ENDCOLOR;
echo ""
sudo ifconfig
echo ""
echo -e $BLUE"[sudo iwconfig]"$ENDCOLOR;
echo ""
sudo iwconfig
echo ""
echo -e $YELLOW"Select the interface you wish to use: [ex. wlan0] "$ENDCOLOR;
read INTERFACE

echo -e $BLUE"Running airmon-ng check.. "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo rfkill unblock all]"$ENDCOLOR;
echo ""
sudo rfkill unblock all
echo ""
echo -e $BLUE"[sudo airmon-ng]"$ENDCOLOR;
echo ""
sudo airmon-ng
echo ""
echo -e $BLUE"[sudo airmon-ng check kill]"$ENDCOLOR;
echo ""
sudo airmon-ng check kill
echo ""

echo -e $BLUE"Would you like to update ieee-data? [y/n] "$ENDCOLOR;
read UPDATEOUI

if [[ $UPDATEOUI = 'Y' || $UPDATEOUI = 'y' ]] ; then

  sudo update-ieee-data
  sudo airodump-ng-oui-update

else 

  echo -e $BLUE"Okay. Maybe later."$ENDCOLOR;

fi 

echo -e $BLUE"Complete.  Good to go. "$ENDCOLOR;
echo ""

echo -e $BLUE"Starting Airmon-ng for $INTERFACE "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo airmon-ng start $INTERFACE]"$ENDCOLOR;
echo ""
sudo airmon-ng start $INTERFACE
echo ""
echo -e $YELLOW"Enter the name of the interface created: [ex. mon0] "$ENDCOLOR;
read MON0

echo -e $BLUE"Let's stay anonymous.  Configuring $MON0 "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo ifconfig $MON0 down]"$ENDCOLOR;
echo ""
sudo ifconfig $MON0 down
echo ""
echo -e $BLUE"Setting new MAC Address "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo macchanger $MON0 -bra]"$ENDCOLOR;
echo ""
sudo macchanger $MON0 -bra
echo ""
echo -e $BLUE"Configuring $MON0 for iw compatibility "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo iw dev $MON0 set type monitor]"$ENDCOLOR;
echo ""
sudo iw dev $MON0 set type monitor
echo ""

echo -e $BLUE"Setting $MON0 to promisc mode "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo ifconfig $MON0 promisc]"$ENDCOLOR;
echo ""
sudo ifconfig $MON0 promisc
echo ""
echo -e $BLUE"Okay.  We are ready to bring $MON0 back up "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo ifconfig $MON0 up]"$ENDCOLOR;
echo ""
sudo ifconfig $MON0 up
echo ""
echo -e $BLUE"Configuration for $MON0 complete. "$ENDCOLOR;
echo ""
echo -e $BLUE"[sudo iw $MON0 info]"$ENDCOLOR;
echo ""
sudo iw $MON0 info
sleep 1
echo ""
echo -e $BLUE"Initializing $MON0 for capture "$ENDCOLOR;
echo ""
echo -e $YELLOW"Specify channel(s)? [y/n] "$ENDCOLOR
read specchannel

if [[ $specchannel = Y || $specchannel = y ]] ; then

  echo -e $YELLOW"Use Preferred Channel(s): y/n [channels 1,3,6,9,11] "$ENDCOLOR;
  read prefchan

  if [[ $prefchan = y || $prefchan = Y ]] ; then

    echo -e $BLUE"Selecting Preferred Channels: 1,3,6,9,11 "$ENCOLOR;
    attachan="1,3,6,9,11"

  else

    echo -e $YELLOW"Specify Channel(s): "$ENDCOLOR;
    read specchan
    CHANOPT="-c $specchan"
    echo ""

  fi

else

  echo -e $BLUE"Selecting all channels "$ENDCOLOR;
  CHANOPTS=" "
  sleep 0.5

fi

echo -e $YELLOW"Specify Options: [enter '-p' for preferred or '--help'] "$ENDCOLOR;
read OPTIONS
while [ -n "$OPTIONS" ] ; do
        case "$OPTIONS" in
                --help)
                        echo -e "
  Options:
      --ivs                 : Save only captured IVs
      --gpsd                : Use GPSd
      --write      <prefix> : Dump file prefix
      -w                    : same as --write
      --beacons             : Record all beacons in dump file
      --update       <secs> : Display update delay in seconds
      --showack             : Prints ack/cts/rts statistics
      -h                    : Hides known stations for --showack
      -f            <msecs> : Time in ms between hopping channels
      --berlin       <secs> : Time before removing the AP/client
                              from the screen when no more packets
                              are received (Default: 120 seconds)
      -r             <file> : Read packets from that file
      -x            <msecs> : Active Scanning Simulation
      --manufacturer        : Display manufacturer from IEEE OUI list
      --uptime              : Display AP Uptime from Beacon Timestamp
      --wps                 : Display WPS information (if any)
      --output-format
                  <formats> : Output format. Possible values:
                              pcap, ivs, csv, gps, kismet, netxml
      --ignore-negative-one : Removes the message that says
                              fixed channel <interface>: -1
      --write-interval
                  <seconds> : Output file(s) write interval in seconds

  Filter options:
      --encrypt   <suite>   : Filter APs by cipher suite
      --netmask <netmask>   : Filter APs by mask
      --bssid     <bssid>   : Filter APs by BSSID
      --essid     <essid>   : Filter APs by ESSID
      --essid-regex <regex> : Filter APs by ESSID using a regular
                              expression
      -a                    : Filter unassociated clients

  By default, airodump-ng hop on 2.4GHz channels.
  You can make it capture on other/specific channel(s) by using:
      --channel <channels>  : Capture on specific channels
      --band <abg>          : Band on which airodump-ng should hop
      -C    <frequencies>   : Uses these frequencies in MHz to hop
      --cswitch  <method>   : Set channel switching method
                    0       : FIFO (default)
                    1       : Round Robin
                    2       : Hop on last
      -s                    : same as --cswitch

      --help                : Displays this usage screen

  Preferred options, these are just my personal options...
    -p : includes options '--showack --band abg --wps -aMU --cswitch 1 --berlin 180 --update 2'"

                        ;;
                -p)
                        echo -e $BLUE"Options received: $SETOPTIONS "$ENDCOLOR;
                        sleep 2
			echo ""

                        echo -e $BLUE"REC:LOG > Saving capture to $CAPTUREPAH/$now.dump "$ENDCOLOR;
                        sleep 2
			echo ""

                        echo -e $YELLOW"Running sequence: airodump-ng $SETOPTIONS $CHANOPT $MON0 -w $CAPTUREPATH/$now.dump "$ENDCOLOR;
                        sleep 2

                        airodump-ng $SETOPTIONS $CHANOPT $MON0 -w $CAPTUREPATH/$now.dump
                        

                        ## todo
                        ## echo -e $YELLOW"Would you like to decrypt the capture with Airdecap? "$ENDCOLOR;
                        ## todo

                        echo -e $BLUE"###############################################"$ENDCOLOR
                        echo -e $YELLOW"#              Operation complete.            #"$ENDCOLOR
                        echo -e $BLUE"###############################################"$ENDCOLOR
                        echo ""
                        echo -e $YELLOW"Have A Solid Day "$ENDCOLOR;
                        echo ""
                        exit 0
                        ;;

                *)      echo -e $BLUE"Options received: $OPTIONS "$ENDCOLOR;
                        echo ""
			sleep 2

                        echo -e $BLUE"REC:LOG > Saving capture to $CAPTUREPATH/$now.dump "$ENDCOLOR;
                        echo ""
			sleep 2

                        echo -e $YELLOW"Running sequence: airodump-ng $OPTIONS $CHANOPT $MON0 -w $CAPTUREPATH/$now.dump "$ENDCOLOR;
                        sleep 2
                        echo ""
                        sudo airodump-ng $OPTIONS $CHANOPT $MON0 -w $CAPTUREPATH/$now.dump
                        

                        echo -e $BLUE"###############################################"$ENDCOLOR
                        echo -e $YELLOW"#              Operation complete.            #"$ENDCOLOR
                        echo -e $BLUE"###############################################"$ENDCOLOR
                        echo ""
                        echo -e $YELLOW"Have A Solid Day "$ENDCOLOR;
                        echo ""
                        exit 0
                        ;;
        esac

        shift # Get next argument
done
