#!/bin/bash

sudo apt-get update

cd ~/

echo -e "Downloading install.txt"
sleep 1
echo ""

wget http://pi.cs.man.ac.uk/download/install.txt | bash
echo ""

echo -e "Installing necessary pre-requesites.."
sleep 1

sudo apt-get install python3-pifacedigitalio python-pifacedigitalio

sudo apt-get install python3-pifacedigital-emulator

sudo apt-get install python3-pifacedigital-scratch-handler

echo -e "Do you want to reboot now? (y/n) "
read REBOOTNOW

if [[ $REBOOTNOW = 'y' || $REBOOTNOW = 'Y' ]] ; then
sudo reboot

else

echo -e "Okay. Maybe later"
fi

