#!/bin/bash
clear
# color vars
RED="\033[1;31m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
CYAN="\033[1;36m"
ENDCOLOR="\033[0m"
# script vars
fileName=art-zero.zip
downloadArt_default="yes"
art_zero_alias="alias goto-artwork='cd $HOME/Pictures/Solid_Art'"
art_zero_location="http://solidoptionos.com/assets/$fileName"
art_zero_path="$HOME/Pictures/Solid_Art/"


echo -e $RED" #################################################################"$ENDCOLOR;
echo -e $YELLOW"    ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"   / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW"  _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW" /___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                          /_/                                  "$ENDCOLOR;
echo -e $RED" #################################################################"$ENDCOLOR;
echo ""
echo ""
echo -e $CYAN"Download artwork from the Solid Option gallery."$ENDCOLOR;
sleep 1
echo ""
read -p "Would you like to download artwork from the Solid Option gallery? [$downloadArt_default] " downloadArt_default 
downloadArt=${downloadArt:-$downloadArt_default}

if [[ $downloadArt = $downloadArt_default || $downloadArt = 'yes' || $downloadArt = 'Y' || $downloadArt = 'y' ]]; then
  
  echo ""
  echo -e $BLUE"Creating Solid Art folder in '$art_zero_path'.."$ENDCOLOR;
  echo ""
  mkdir -p $art_zero_path
  cd $art_zero_path
  pwd
  echo ""

  echo -e $BLUE"Downloading artwork.."$ENDCOLOR; 
  echo ""
  wget $art_zero_location
  echo ""

  echo -e $BLUE"Extracting artwork.."$ENDCOLOR;
  echo ""
  unzip $fileName
  echo ""

  echo -e $BLUE"Cleaning up.."$ENDCOLOR;
  echo ""
  rm -rf __MAC*
  rm $fileName
  ls -Al
  echo ""

  echo -e $BLUE"Adding $art_zero_alias to '$HOME/.bashrc'.."$ENDCOLOR;
  echo ""
  echo "$art_zero_alias" >> $HOME/.bashrc
  echo ""

  echo -e $CYAN"Complete. Enjoy!!"$ENDCOLOR;
  exit

else

  echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
  exit

fi
