#!/bin/bash

# color vars
RED="\033[1;31m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
CYAN="\033[1;36m"
ENDCOLOR="\033[0m"
# end color vars

# Enter script name
NAME="enter script name"

clear
echo -e $RED" #################################################################"$ENDCOLOR; 
echo -e $YELLOW"    ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"   / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW"  _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW" /___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                          /_/                                  "$ENDCOLOR;
echo -e $RED" #################################################################"$ENDCOLOR;
echo ""
echo ""
echo -e $CYAN"$NAME"$ENDCOLOR;
sleep 1
echo ""

CLEANPURGE_DEFAULT="Y"
read -p "Would you like to setup headless mode on your raspberry pi? [$CLEANPURGE_DEFAULT/n] " CLEANPURGE_DEFAULT
CLEANPURGE=${CLEANPURGE:-$CLEANPURGE_DEFAULT}

if [[ $CLEANPURGE = 'y' || $CLEANPURGE = '$CLEANPURGE_DEFAULT' ]] ; then

	echo ""
	echo -e $YELLOW""$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt autoremove]"$ENDCOLOR;
	echo ""
	sudo apt autoremove
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt-fast clean && apt-fast autoclean]"$ENDCOLOR;
	echo ""
	sudo apt-fast clean && sudo apt-fast autoclean
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt clean && apt autoclean]"$ENDCOLOR;
	echo ""
	sudo apt clean && sudo apt autoclean
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""
	
	echo -e $BLUE"[apt purge]"$ENDCOLOR;
	echo ""
        sudo apt purge
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[rm -rf /var/cache/apt/archives/]"$ENDCOLOR;
	echo ""
	sudo rm -rf -i /var/cache/apt/archives/
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

        echo -e $CYAN"Clean and Purge Complete"$ENDCOLOR;
        echo ""
	clear

else
	echo ""
	echo -e $CYAN"Okay. Maybe later"$ENDCOLOR;
	echo ""

fi

echo -e $CYAN"Checking for unconfigured packages.."$ENDCOLOR;
echo ""
echo -e $BLUE"[dpkg --configure -a]"$ENDCOLOR;
sudo dpkg --configure -a
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

UPDATEOP_DEFAULT="apt"
read -p "Would you like to update with apt or aptitude? [$UPDATEOP_DEFAULT/aptitude]" UPDATEOP_DEFAULT
UPDATEOP=${UPDATEOP:-$UPDATEOP_DEFAULT}

if [[ $UPDATEOP = '$UPDATE_DEFAULT' || $UPDATEOP = 'apt' ]] ; then

	echo -e $CYAN"Updating packages.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt update]"$ENDCOLOR;
	echo ""
	sudo apt update
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $CYAN"Removing any older packages before upgrade.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt autoremove]"$ENDCOLOR;
	echo ""
	sudo apt autoremove
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $CYAN"Installing any missing dependencies.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt -f install]"$ENDCOLOR;
	echo ""
	sudo apt -f install
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $CYAN"Upgrading packages.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt upgrade]"$ENDCOLOR;
	echo ""
	sudo apt upgrade
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt dist-upgrade]"$ENDCOLOR;
	echo ""
	sudo apt dist-upgrade 
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""
fi

if [[ $UPDATEOP = 'aptitude' || $UPDATEOP = 'APTITUDE' ]] ; then

        echo -e $CYAN"Updating packages.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude update]"$ENDCOLOR;
        echo ""
        sudo aptitude update
        echo -e $CYAN"Complete."$ENDCOLOR;
       	echo ""

        echo -e $CYAN"Removing any older packages before upgrade.."$ENDCOLOR;
        echo ""
        echo -e $BLUE"[apt autoremove]"$ENDCOLOR;
        echo ""
        sudo apt autoremove
        echo -e $CYAN"Complete."$ENDCOLOR;
      	echo ""

        echo -e $CYAN"Installing any missing dependencies.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude -f install]"$ENDCOLOR;
        echo ""
        sudo aptitude -f install
	echo -e $CYAN"Complete."$ENDCOLOR;
        echo ""

        echo -e $CYAN"Upgrading packages.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude upgrade]"$ENDCOLOR;
        echo ""
        sudo aptitude upgrade
	echo -e $CYAN"Complete."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude dist-upgrade]"$ENDCOLOR;
        echo ""
        sudo aptitude dist-upgrade
	echo -e $CYAN"Complete."$ENDCOLOR;
        echo ""
fi

fixornot_default="Y"
read -p "Would you like to try and repair any broken packages? [$fixornot_default/n] " fixornot_defualt
fixornot=${fixornot:-$fixornot_default}

if [[ $fixornot = 'y' || $fixornot = 'Y' ]] ; then

	echo ""
	echo -e $CYAN"OK. Attempting to repair broken packages.. "$ENDCOLOR;
	echo ""
	
	echo -e $BLUE"[dpkg --configure -a]"$ENDCOLOR;
	echo ""
	sudo dpkg --configure -a
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""
	
	echo -e $BLUE"[apt update --fix-missing]"$ENDCOLOR;
	echo ""
	sudo apt update --fix-missing
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt upgrade --fix-broken]"$ENDCOLOR;
	echo ""
	sudo apt upgrade --fix-broken
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt -f install]"$ENDCOLOR;  
        echo ""
	sudo apt -f install
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

else

	echo ""
        echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        echo ""

fi
	
moproblems_default="N"
read -p "Run aptitude -f install --full-resolver? [$moproblems_default/y]" moproblems_default
moproblems=${moproblems:-$moproblems_default}

if [[ $moproblems = 'y' || $moproblems = 'Y' ]] ; then	
	echo ""
	echo -e $CYAN"Attempting fix with full-resolver.."$ENDCOLOR;
	echo ""
	echo -e $RED"This may take a while.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[aptitude -f install --full-resolver]"$ENDCOLOR;
	echo ""
	sudo aptitude -f install --full-resolver
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

else
 		
        echo ""
	echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        echo ""

fi

APTFILE_DEFAULT="Y"
read -p "Would you like to install and update apt-file? [$APTFILE_DEFAULT/n] " APTFILE_DEFAULT
APTFILE=${APTFILE:-$APTFILE_DEFAULT}

if [[ $APTFILE = 'y' || $APTFILE = '$APTFILE_DEFAULT' ]] ; then

        echo ""
        echo -e $CYAN"Installing and/or updating apt-file"$ENDCOLOR;
        echo ""

	echo -e $BLUE"[apt install apt-file]"$ENDCOLOR;
        echo ""
	sudo apt install apt-file -y
	echo -e $CYAN"Complete."$ENDCOLOR;
        echo ""

        echo -e $CYAN"Updating apt-file.. "$ENDCOLOR;
        echo ""
	echo -e $BLUE"[apt-file update]"$ENDCOLOR;
        echo ""
	sudo apt-file update
        echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

else

        echo ""
        echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        echo ""

fi

APTFAST_DEFAULT="Y"
read -p "Would you like to install and update apt-fast? [$APTFAST_DEFAULT/n] " APTFAST_DEFAULT
APTFAST=${APTFAST:-$APTFAST_DEFAULT}

if [[ $APTFAST = 'y' || $APTFAST = '$APTFAST_DEFAULT' ]] ; then 

	echo ""
	echo -e $CYAN"Installing and updating apt-fast.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt install -y aria2 git]"$ENDCOLOR;
	echo ""
	sudo apt install -y aria2 git
	echo -e $CYAN"Complete."$ENDCOLOR;
	echo ""

	if ! [[ -f /usr/bin/apt-fast ]]; then

		if [[ -d "/root/backup/apt-fast" ]];  then

			echo ""
			echo -e $CYAN"Directory already exists, so updating repository.."$ENDCOLOR;
			echo ""
			echo -e $BLUE"[cd /root/backup/apt-fast && sudo git pull]"$ENDCOLOR;
			echo ""
			cd /root/backup/apt-fast && git pull
			echo -e $BLUE"Complete."$ENDCOLOR;
			echo ""
			
			echo -e $CYAN"Moving apt-fast into /usr/bin"$ENDCOLOR;
			echo ""
			echo -e $BLUE"[cp /root/backup/apt-fast/apt-fast /usr/bin]"$ENDCOLOR;
			echo ""
			sudo cp /root/backup/apt-fast/apt-fast /usr/bin
			echo -e $BLUE"Complete."$ENDCOLOR;
			echo ""

			echo -e $CYAN"Making apt-fast executable"$ENDCOLOR;
			echo ""
			echo -e $BLUE"[chmod +x /usr/bin/apt-fast]"$ENDCOLOR;
			echo ""
			sudo chmod +x /usr/bin/apt-fast
			echo -e $BLUE"Complete."$ENDCOLOR;
			echo ""

			echo -e $CYAN"Copying apt-fast.conf to /etc.."$ENDCOLOR;
			echo ""
			echo -e $BLUE"[cp /root/backup/apt-fast/apt-fast.conf /etc]"$ENDCOLOR;
			echo ""
			sudo cp /tmp/apt-fast/apt-fast.conf /etc
			echo -e $BLUE"Complete."$ENDCOLOR;
			echo ""

		fi	
			
		echo -e $BLUE"[git clone https://github.com/ilikenwf/apt-fast.git /root/backup/apt-fast]"$ENDCOLOR;
		echo ""
		git clone https://github.com/ilikenwf/apt-fast /root/backup/apt-fast
		echo -e $CYAN"Complete."$ENDCOLOR;
		echo ""

		echo -e $BLUE"[cp /root/backup/apt-fast/apt-fast /usr/bin]"$ENDCOLOR;
		echo ""
		sudo cp /root/backup/apt-fast/apt-fast /usr/bin
		echo -e $CYAN"Complete."$ENDCOLOR;
		echo ""
		echo -e $BLUE"[chmod +x /usr/bin/apt-fast]"$ENDCOLOR;
		echo ""
		sudo chmod +x /usr/bin/apt-fast
		echo -e $CYAN"Complete."$ENDCOLOR;
		echo ""
		echo -e $BLUE"[cp /root/backup/apt-fast/apt-fast.conf]"$ENDCOLOR;
		echo ""
		sudo cp /root/backup/apt-fast/apt-fast.conf /etc
		echo -e $CYAN"Complete."$ENDCOLOR;
		echo ""

	fi

else 

	echo ""
	echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
	echo ""

fi

echo -e $CYAN"Updating database, menus, USB and PCI IDs."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating menus.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-menus]"$ENDCOLOR;
echo ""
sudo update-menus
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating databases.."$ENDCOLOR;
echo ""
echo -e $BLUE"[updatedb]"$ENDCOLOR;
echo ""
sudo updatedb
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $BLUE"[updatedb.mlocate]"$ENDCOLOR;
echo ""
sudo updatedb.mlocate
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $BLUE"[updatedb.findutils]"$ENDCOLOR;
echo ""
sudo updatedb.findutils
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating USB IDs.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-usbids]"$ENDCOLOR;
echo ""
sudo update-usbids
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating PCI IDs.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-pciids]"$ENDCOLOR;
echo ""
sudo update-pciids
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating binftms.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-binftms]"$ENDCOLOR;
echo ""
sudo update-binftms
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating gsfontmap.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-gsfontmap]"$ENDCOLOR;
echo ""
sudo update-gsfontmap
update-gsfontmap
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating updmap.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-updmap]"$ENDCOLOR;
echo ""
sudo update-updmap
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Configuring updmap for system.."$ENDCOLOR;
echo ""
echo -e $BLUE"[updmap -sys]"$ENDCOLOR;
echo ""
sudo updmap -sys
echo -e $CYAN"Complete."$ENDCOLOR;
echo ""

gemUpdate_default="Y"
read -p "Would you like to update gems? WARNING: THIS WILL TAKE A LONG TIME! [$updateOui_default/n] " gemUpdate_default
gemUpdate=${gemUpdate:-$gemUpdate_default}

if [[ $gemUpdate = 'y' || $gemUpdate = "$gemUpdate_Default" ]] ; then

	echo -e $CYAN"Updating gems.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[gem update]"$ENDCOLOR;
	echo ""
	sudo gem update
	echo -e $BLUE"Complete."$ENDCOLOR;
	echo ""
else
	echo ""
	echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
	echo ""

fi	

updateOui_default="Y"
read -p "Would you like to update-oui? [$updateOui_default/n] " updateOui_default
updateOui=${updateOui:-$updateOui_default}

if [[ $updateOui = 'y' || $updateOui = "$updateOui_Default" ]] ; then

	echo ""
	echo -e $CYAN"Updating ieee-data.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"Upgrading to the latest 'ieee-data'.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt install ieee-data -y]"$ENDCOLOR;
	echo ""
	sudo apt install ieee-data -y
	echo -e $BLUE"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"This may take a while depending on your system."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[airodump-ng-oui-update]"$ENDCOLOR;
	echo ""
	sudo airodump-ng-oui-update
	echo -e $BLUE"Complete."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[update-ieee-data]"$ENDCOLOR;
	echo ""
	sudo update-ieee-data
	echo -e $BLUE"Complete."$ENDCOLOR;
	echo ""

else
\
	echo ""
	echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
	echo ""

fi 

echo -e $CYAN"Updating initramfs.."$ENDCOLOR;
echo ""
sleep 1
echo -e $BLUE"[update-initramfs -uv]"$ENDCOLOR;
echo ""
sudo update-initramfs -uv
echo -e $BLUE"Complete."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating grub and grub2.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-grub && update-grub2]"$ENDCOLOR;
echo ""
sudo update-grub && sudo update-grub2
echo -e $BLUE"Complete."$ENDCOLOR;
echo ""

sleep 1
echo -e $YELLOW"    ____         __              __  __        __      __         __"$ENDCOLOR;
echo -e $YELLOW"   / __/_ _____ / /____ __ _    / / / /__  ___/ /__  _/ /____ ___/ /"$ENDCOLOR;
echo -e $YELLOW"  _\ \/ // (_-</ __/ -_)  ' \  / /_/ / _ \/ _  / _ \`/ __/ -_) _  / "$ENDCOLOR;
echo -e $YELLOW" /___/\_, /___/\__/\__/_/_/_/  \____/ .__/\_,_/\_,_/\__/\__/ \_,_/  "$ENDCOLOR;
echo -e $YELLOW"     /___/                         /_/                             "$ENDCOLOR;
exit

