#!/bin/bash
#Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"
parent=`dirname $PWD`
grandparent=`dirname $parent`
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $BLUE"#                                 ||"$ENDCOLOR;
echo -e $BLUE"#                                 ||_________________________/'|"$ENDCOLOR;
echo -e $BLUE"#                               _| O======/                    |"$ENDCOLOR;
echo -e $BLUE"#                              |_|               ============  |"$ENDCOLOR;
echo -e $BLUE"#                                |  __   ______________________|"$ENDCOLOR;
echo -e $BLUE"#                                |_/  )  (    |___||     O-   /"$ENDCOLOR;
echo -e $BLUE"#  C a r p e   O m n i o u s          (  )    /  / |_________/"$ENDCOLOR;
echo -e $BLUE"#                                     (  )   /  /    | ) |   |"$ENDCOLOR;
echo -e $BLUE"#                                     (__)  /  /     \___|__("$ENDCOLOR;
echo -e $BLUE"#                                          /  /          )   \ "$ENDCOLOR;
echo -e $BLUE"#                                         /  /            )   \ "$ENDCOLOR;
echo -e $BLUE"#                                        /  /              )___\ "$ENDCOLOR;
echo -e $BLUE"#                                       /  / "$ENDCOLOR;
echo -e $BLUE"#                                      /__/"$ENDCOLOR;
echo -e $BLUE"#                                "$ENDCOLOR;
echo ""
echo -e $YELLOW"Create a new user.."$ENDCOLOR;
echo ""
echo -e $YELLOW"This is a post installation script designed for the solid-scripts drive or downloaded OS"$ENDCOLOR;
echo -e $YELLOW" you either purchased or downloaded online to give you a simpler, more robust user experience with the OS and its tools."$ENDCOLOR;

echo -e $YELLOW"Let's get started"$ENDCOLOR;
echo ""
echo ""

homepath_default=$HOME
read -p "Please set your home path (leave out trailing /'s): [$homepath_default] " homepath_default
HOMEPATH=${HOMEPATH:-$homepath_default}
echo ""
echo -e $BLUE"Your home path is set to $HOMEPATH/."$ENDCOLOR;
echo ""
aliases_default="Y"
read -p "Do you want to add custom alias to your bashrc? [$aliases_default/n] " aliases_default
aliases=${aliases:-$aliases_default}

if [[ $aliases = "aliases_default" || $aliases = 'y' ]] ; then
	
  echo ""
  echo -e $BLUE"Adding aliases to .bashrc.."$ENDCOLOR;
  echo ""
  touch $HOMEPATH/.bash_aliases
  echo "alias ll='ls -Al'" >> $HOMEPATH/.bash_aliases
  echo "alias lz='ls -Zla'" >> $HOMEPATH/.bash_aliases
  echo "alias xclip='xclip -selection c'" >> $HOMEPATH/.bash_aliases
  echo "alias goto-solid-scripts='cd $HOMEPATH/solid-scripts/'" >> $HOMEPATH/.bash_aliases
  echo ""

else

  echo -e $YELLOW"Okay. Maybe later."$ENDCOLOR;
  echo ""

fi

NEWUSER_DEFAULT="Y"
read -p "Would you like to create a standard user? [$NEWUSER_DEFAULT/n] " NEWUSER_DEFAULT
NEWUSER=${NEWUSER:-$NEWUSER_DEFAULT}

if [[ $NEWUSER = "NEWUSER_DEFAULT" || $NEWUSER = 'y' ]] ; then 

  echo -e $YELLOW"Username: [enter username] "$ENDCOLOR;
  read USERNAME
  echo ""
	
  echo -e $BLUE"Creating standard user, $USERNAME.."$ENDCOLOR;
  echo ""
  echo ""
  sudo useradd -m $USERNAME
  echo -e $GREEN"Complete."$ENDCOLOR;
  echo ""

  echo -e $BLUE"Creating home directories for $USERNAME..."$ENDCOLOR;
  echo ""
  sudo mkdir -p /home/$USERNAME/Downloads
  sudo mkdir -p /home/$USERNAME/Pictures
  sudo mkdir -p /home/$USERNAME/Documents
  sudo mkdir -p /home/$USERNAME/Desktop
  sudo chown -R $USERNAME:$USERNAME /home/$USERNAME
  sudo chmod -R 777 /home/$USERNAME
  echo ""

  echo -e $BLUE"Adding $USERNAME to sudo group."$ENDCOLOR;
  sudo usermod -aG sudo $USERNAME
  echo ""
	
  echo -e $BLUE"Adding $USERNAME to adm group."$ENDCOLOR;
  sudo usermod -aG adm $USERNAME
  echo ""
        
  echo -e $BLUE"Adding $USERNAME to kismet group."$ENDCOLOR;
  sudo usermod -aG kismet $USERNAME
  echo ""
	
  echo -e $BLUE"Adding $USERNAME to netdev group."$ENDCOLOR;
  sudo usermod -aG netdev $USERNAME
  echo ""
	
  echo -e $BLUE"Adding $USERNAME to root group."$ENDCOLOR;
  sudo usermod -aG root $USERNAME
  echo ""
	
  echo -e $BLUE"Adding $USERNAME to wireshark group."$ENDCOLOR;
  sudo usermod -aG wireshark $USERNAME
  echo ""

  echo -e $BLUE"Updating $USERNAME shell to /bin/bash.."$ENDCOLOR;
  sudo usermod -s /bin/bash $USERNAME
  echo ""
  echo ""

  echo -e $BLUE"Adding $USERNAME to /etc/sudoers.."$ENDCOLOR;
  sudo sed -i 's/\#\ Allow\ members\ of\ group\ sudo\ to\ execute\ any\ command/'$USERNAME'\	ALL\=\(ALL\:ALL\)\ ALL\' >> /etc/sudoers
  echo ""
  sudo cat /etc/sudoers

  echo -e $YELLOW"Set a password for $USERNAME.."$ENDCOLOR;
  echo ""
  sudo passwd $USERNAME
  echo ""
  echo ""
  clonebashrc_default="Y"	
  read -p "Do you want to clone root .bashrc to $USERNAME .bashrc? [$clonebashrc_default/n] " clonebashrc_default
  clonebashrc=${clonebashrc:-$clonebashrc_default}

  if [[ $clonebashrc = "clonebashrc_default" || $clonebashrc = "y" ]] ; then 
	
    echo -e $BLUE"Cloning /root/.bashrc to /home/$USERNAME/.bashrc.."$ENDCOLOR;
    echo ""
    echo -e $BLUE"Backing up first.."$ENDCOLOR; 
    echo ""
    sudo mkdir -p /home/$USERNAME
    echo ""
    sudo cp /home/$USERNAME/.bashrc /home/$USERNAME/.bashrc.bak
    echo ""
    echo -e $GREEN"Complete."$ENDCOLOR;
    echo ""
    echo -e $BLUE"Cloning.."$ENDCOLOR;
    echo ""
    sudo cp /root/.bashrc /home/$USERNAME/.bashrc
    sudo chown $USERNAME:$USERNAME /home/$USERNAME/.bashrc
    sudo chmod 777 /home/$USERNAME/.bashrc 
    echo -e $GREEN"Complete."$ENDCOLOR;
    echo ""
    echo -e $GREEN"$USERNAME Setup Complete."$ENDCOLOR;
    echo ""

  else

    echo -e $YELLOW"Okay. Maybe later."$ENDCOLOR;
    echo ""
    echo ""
	
  fi

else

  echo -e $YELLOW"Okay. Maybe later."$ENDCOLOR;
  echo ""
  echo ""

fi
echo -e $BLUE"Wrapping up the post install with necessary updates.."$ENDCOLOR;
echo ""
echo ""

echo -e $BLUE"[updatedb]"$ENDCOLOR;
echo ""
sudo updatedb -v --prunepaths /mnt

echo -e $BLUE"[updatedb.mlocate]"$ENDCOLOR;
echo ""
sudo updatedb.mlocate -v --prunepaths /mnt

echo -e $BLUE"[update-menus]"$ENDCOLOR;
echo ""
sudo update-menus

echo -e $BLUE"[update-usbids]"$ENDCOLOR;
echo ""
sudo update-usbids

echo -e $BLUE"[update-pciids]"$ENDCOLOR;
echo ""
sudo update-pciids

echo -e $BLUE"[update-initramfs -uv]"$ENDCOLOR;
echo ""
sudo update-initramfs -uv

echo -e $BLUE"[update-grub]"$ENDCOLOR;
echo ""
sudo update-grub

echo -e $BLUE"[update-grub2]"$ENDCOLOR;
echo ""
sudo update-grub2

echo -e $BLUE"Syncing.."$ENDCOLOR;
echo ""
sync

echo ""
echo -e $GREEN"Wrap up complete."$ENDCOLOR;
echo ""
echo ""
echo -e $BLUE"#################################"$ENDCOLOR;
echo -e $YELLOW"#      Operation Complete.       #"$ENDCOLOR;
echo -e $BLUE"#################################"$ENDCOLOR;
echo ""

