#!/bin/bash

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 165D673674A995B3E64BF0CF4F191A5A8844C542
gpg -a --export 165D673674A995B3E64BF0CF4F191A5A8844C542 | sudo apt-key add -

#sudo apt-key adv --keyserver keyserver.ubuntu,com --recv F0B5D826
#gpg -a --export 4FF2E40CEC39A57852C12BAF77589CABF0B5D826 | sudo apt-key add - 

#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E06E6293 
#gpg -a --export DED04C8CBB517AE45B073F12A5D712AEE06E6293 | sudo apt-key add - 

#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv F59EAE4D
#gpg -a --export 4FA44A478284A18C1BA4A9CAD530E028F59EAE4D | sudo apt-key add - 

#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv F0B5D826
#gpg -a --export 4FF2E40CEC39A57852C12BAF77589CABF0B5D826 | sudo apt-key add -
