#!/bin/bash

echo "cd into $HOME/Downloads folder..";
echo ""
cd ~/Downloads 

echo "Fteching script..";
echo ""
sleep 1
sudo wget http://www.fars-robotics.net/install-wifi -O /usr/bin/install-wifi
echo ""

echo "Copying the executable file, install-wifi to /usr/bin..";
echo ""
sleep 1
sudo chmod +x /usr/bin/install-wifi
echo ""

echo "Displaying the help menu..";
echo ""
sleep 1
sudo install-wifi -h
echo ""

echo "Modifying script to fit your system..";
echo ""
sleep 1

sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

echo ""
echo "Installing bc..";
echo ""
sleep 1
sudo apt-get install bc -y

echo "Sourcing rpi-source --skip-gcc..";
echo ""
sleep 1
rpi-source --skip-gcc

echo "Upgrading..";
echo ""
sleep 1
sudo apt-get upgrade



echo ""
echo "Entering /lib/modules/4.9.25+/build.."
echo ""
cd /lib/modules/$(uname -r)/build
echo  ""

echo "Making module.."
echo ""
make

