#!/bin/bash
echo "Installing aria2 and git..";
echo ""

sudo apt-get install -y aria2 git

echo "Installing apt-fast..";
echo ""

if ! [[ -f /usr/bin/apt-fast ]]; then
  git clone https://github.com/ilikenwf/apt-fast /tmp/apt-fast
  sudo cp /tmp/apt-fast/apt-fast /usr/bin
  sudo chmod +x /usr/bin/apt-fast
  sudo cp /tmp/apt-fast/apt-fast.conf /etc
fi
echo "Done."

