#!/bin/bash -c
echo "Apt-fast is a shell wrapper script that speeds up the updating and upgrading of apt-get.";
echo ""
sleep 1
echo "Installing Apt-Fast..";
echo ""
"$(curl -sL https://git.io/vokNn)"
