#!/bin/bash
# color vars
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1:37m"
ENDCOLOR="\033[0m"
# end color vars

clear
echo -e $RED" #################################################################"$ENDCOLOR; 
echo -e $YELLOW"    ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"   / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW"  _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW" /___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                          /_/                                  "$ENDCOLOR;
echo -e $RED" #################################################################"$ENDCOLOR;
echo ""
echo ""
echo -e $CYAN"Solid-Update"$ENDCOLOR;
sleep 1
echo ""
CLEANPURGE_DEFAULT="Y"
read -p "Would you like to clean and purge first? [$CLEANPURGE_DEFAULT/n] " CLEANPURGE_DEFAULT
CLEANPURGE=${CLEANPURGE:-$CLEANPURGE_DEFAULT}

if [[ $CLEANPURGE = 'y' || $CLEANPURGE = '$CLEANPURGE_DEFAULT' ]] ; then

	echo ""
	echo -e $YELLOW"Running Clean and Purge.. "$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt-get autoremove]"$ENDCOLOR;
	echo ""
	sudo apt-get autoremove
	echo ""

	echo -e $BLUE"[apt-get clean]"$ENDCOLOR;
	echo ""
	sudo apt-get clean
	echo ""
	
	echo -e $BLUE"[apt-get purge]"$ENDCOLOR;
	echo ""
        sudo apt-get purge
	echo ""

	echo -e $BLUE"[rm -rf /var/cache/apt/archives/]"$ENDCOLOR;
	echo ""
	sudo rm -rf /var/cache/apt/archives/
	echo ""

        echo -e $CYAN"Clean and Purge Complete"$ENDCOLOR;
        echo ""
	clear

else
	echo ""
	echo -e $CYAN"Okay. Maybe later"$ENDCOLOR;
	echo ""

fi
echo -e $CYAN"Checking for unconfigured packages.."$ENDCOLOR;
echo ""
sudo dpkg --configure -a
echo ""

UPDATEOP_DEFAULT="APT"
read -p "Would you like to update with apt or aptitude? [$UPDATEOP_DEFAULT/aptitude]" UPDATEOP_DEFAULT
UPDATEOP=${UPDATEOP:-$UPDATEOP_DEFAULT}

if [[ $UPDATEOP = '$UPDATE_DEFAULT' || $UPDATEOP = 'apt' ]] ; then

	echo -e $CYAN"Updating packages.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt-get update]"$ENDCOLOR;
	echo ""
	sudo apt-get update
	echo ""

	echo -e $CYAN"Removing any older packages before upgrade.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt-get autoremove]"$ENDCOLOR;
	echo ""
	sudo apt-get autoremove
	echo ""

	echo -e $CYAN"Installing any missing dependencies.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt-get -f install]"$ENDCOLOR;
	echo ""
	sudo apt-get -f install
	echo ""

	echo -e $CYAN"Upgrading packages.."$ENDCOLOR;
	echo ""

	echo -e $BLUE"[apt-get upgrade]"$ENDCOLOR;
	echo ""
	sudo apt-get upgrade
	echo ""

	echo -e $BLUE"[apt-get dist-upgrade]"$ENDCOLOR;
	echo ""
	sudo apt-get dist-upgrade 
	echo ""
fi

if [[ $UPDATEOP = 'aptitude' || $UPDATEOP = 'APTITUDE' ]] ; then

        echo -e $CYAN"Updating packages.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude update]"$ENDCOLOR;
        echo ""
        sudo aptitude update
        echo ""

        echo -e $CYAN"Removing any older packages before upgrade.."$ENDCOLOR;
        echo ""
        echo -e $BLUE"[apt-get autoremove]"$ENDCOLOR;
        echo ""
        sudo apt-get autoremove
        echo ""

        echo -e $CYAN"Installing any missing dependencies.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude -f install]"$ENDCOLOR;
        echo ""
        sudo aptitude -f install
        echo ""

        echo -e $CYAN"Upgrading packages.."$ENDCOLOR;
        echo ""

        echo -e $BLUE"[aptitude upgrade]"$ENDCOLOR;
        echo ""
        sudo aptitude upgrade
        echo ""

        echo -e $BLUE"[aptitude dist-upgrade]"$ENDCOLOR;
        echo ""
        sudo aptitude dist-upgrade 
        echo ""
fi  
echo ""
fixornot_default="Y"
read -p "Would you like to try and repair any broken packages? [$fixornot_default/n] " fixornot_defualt
fixornot=${fixornot:-$fixornot_default}

if [[ $fixornot = 'y' || $fixornot = 'Y' ]] ; then

	echo ""
	echo -e $CYAN"OK. Attempting to repair broken packages.. "$ENDCOLOR;
	echo ""
	echo -e $BLUE"[apt-get update --fix-missing]"$ENDCOLOR;
	echo ""
	sudo apt-get update --fix-missing
	echo ""

	echo -e $BLUE"[apt-get upgrade --fix-broken]"$ENDCOLOR;
	echo ""
	sudo apt-get upgrade --fix-broken
	echo ""

	echo -e $BLUE"[apt-get -f install]"$ENDCOLOR;  
        echo ""
	sudo apt-get -f install
	echo ""

else

	echo ""
        echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        echo ""

fi
	
moproblems_default="N"
read -p "Run aptitude -f install --full-resolver? [$moproblems_default/y]" moproblems_default
moproblems=${moproblems:-$moproblems_default}

        if [[ $moproblems = 'y' || $moproblems = 'Y' ]] ; then	
		echo ""
		echo -e $CYAN"Attempting fix with full-resolver.."$ENDCOLOR;
		echo ""
		echo -e $RED"This may take a while.."$ENDCOLOR;
		echo ""
		echo -e $BLUE"[aptitude -f install --full-resolver]"$ENDCOLOR;
		echo ""
		sudo aptitude -f install --full-resolver
		echo ""
	
	else
 		
        	echo ""
		echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        	echo ""

	fi

APTFILE_DEFAULT="Y"
read -p "Would you like to install and update apt-file? [$APTFILE_DEFAULT/n] " APTFILE_DEFAULT
APTFILE=${APTFILE:-$APTFILE_DEFAULT}

if [[ $APTFILE = 'y' || $APTFILE = '$APTFILE_DEFAULT' ]] ; then

        echo ""
        echo -e $CYAN"Installing and/or updating apt-file"$ENDCOLOR;
        echo ""
        sudo apt-get install apt-file -y
        echo ""

        echo -e $CYAN"Updating apt-file.. "$ENDCOLOR;
        echo ""
        echo -e $RED"This may take a while depending on your system. "$ENDCOLOR;
        echo ""
        sudo apt-file update
        echo ""

else

        echo ""
        echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
        echo ""

fi

echo -e $CYAN"Updating database, menus, USB and PCI IDs."$ENDCOLOR;
echo ""

echo -e $CYAN"Updating menus.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-menus]"$ENDCOLOR;
echo ""
sudo update-menus
echo ""

echo -e $CYAN"Updating database.."$ENDCOLOR;
echo ""
echo -e $BLUE"[updatedb]"$ENDCOLOR;
echo ""
sudo updatedb
echo ""

echo -e $CYAN"Updating USB IDs.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-usbids]"$ENDCOLOR;
echo ""
sudo update-usbids
echo ""

echo -e $CYAN"Updating PCI IDs.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-pciids]"$ENDCOLOR;
echo ""
sudo update-pciids
echo ""

updateOui_default="Y"
read -p "Would you like to update-oui? [$updateOui_default/n] " updateOui_default
updateOui=${updateOui:-$updateOui_default}

if [[ $updateOui = 'y' || $updateOui = "$updateOui_Default" ]] ; then

	echo ""
	echo -e $CYAN"Updating ieee-data.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"Upgrading to the latest 'ieee-data'.."$ENDCOLOR;
	echo ""
	sudo apt-get install --reinstall ieee-data -y
	echo ""
	echo -e $BLUE"This may take a while depending on your system."$ENDCOLOR;
	echo ""
	sudo update-oui
	sudo update-ieee-data
	echo ""
	sleep 1
else
	echo ""
	echo -e $CYAN"Okay. Maybe later."$ENDCOLOR;
	echo ""

fi

clear 

echo -e $CYAN"Updating initramfs.."$ENDCOLOR;
echo ""
sleep 1
echo -e $BLUE"[update-initramfs -uv]"$ENDCOLOR;
echo ""
sudo update-initramfs -uv
echo ""
echo -e $CYAN"Updating grub and grub2.."$ENDCOLOR;
echo ""
echo -e $BLUE"[update-grub && update-grub2]"$ENDCOLOR;
echo ""
sudo update-grub && sudo update-grub2
echo ""
sleep 1
echo -e $YELLOW"    ____         __              __  __        __      __         __"$ENDCOLOR;
echo -e $YELLOW"   / __/_ _____ / /____ __ _    / / / /__  ___/ /__  _/ /____ ___/ /"$ENDCOLOR;
echo -e $YELLOW"  _\ \/ // (_-</ __/ -_)  ' \  / /_/ / _ \/ _  / _ \`/ __/ -_) _  / "$ENDCOLOR;
echo -e $YELLOW" /___/\_, /___/\__/\__/_/_/_/  \____/ .__/\_,_/\_,_/\__/\__/ \_,_/  "$ENDCOLOR;
echo -e $YELLOW"     /___/                         /_/                             "$ENDCOLOR;
exit
