#!/bin/bash
echo "Restarting Network";
echo ""
sleep 1
echo "[sudo /etc/init.d/networking stop]";
sudo /etc/init.d/networking stop
sleep 1
echo "[sudo /etc/init.d/network-manager stop]";
sudo /etc/init.d/network-manager stop
sleep 1
echo "[sudo /etc/init.d/networking start]";
sudo /etc/init.d/networking start
sleep 1
echo "[sudo /etc/init.d/network-manager start]";
sudo /etc/init.d/network-manager start
sleep 1
echo "[sudo service wpa_supplicant start]";
sudo service wpa_supplicant start
sleep 1
echo "[sudo systemctl restart systemd-resolved.service]";
sudo systemctl restart systemd-resolved.service
sleep 1

#echo "[sudo /etc/init.d/networking restart]";
#sudo /etc/init.d/networking restart
#sleep 1
#echo "[sudo /etc/init.d/network-manager restart]";
#sudo /etc/init.d/network-manager restart
#sleep 1

#echo "[sudo ifconfig eth0 down]";
#sudo ifconfig eth0 down
sleep 1
echo "[sudo ifconfig wlan0 down]";
sudo ifconfig wlan0 down 
sleep 1
echo "[sudo ifconfig wlan1 down]";
sudo ifconfig wlan1 down
sleep 1
echo "[sudo ifconfig wlan2 down]";
sudo ifconfig wlan2 down
sleep 1
echo "[sudo ifconfig wlan3 down]";
sudo ifconfig wlan3 down
sleep 1
echo "[sudo ifconfig wlan4 down]";
sudo ifconfig wlan4 down
sleep 1

echo "[sudo iwconfig wlan0 txpower 3000]";
sudo iwconfig wlan0 txpower 3000
sleep 1
echo "[sudo iwconfig wlan0 txpower 3000]";
sudo iwconfig wlan1 txpower 3000
sleep 1
echo "[sudo iwconfig wlan0 txpower 3000]";
sudo iwconfig wlan2 txpower 3000
sleep 1
echo "[sudo iwconfig wlan0 txpower 3000]";
sudo iwconfig wlan3 txpower 3000
sleep 1
echo "[sudo iwconfig wlan0 txpower 3000]";
sudo iwconfig wlan4 txpower 3000
sleep 1

echo "[sudo ifconfig wlan0 up]";
sudo ifconfig eth0 up
sleep 1
echo "[sudo ifconfig wlan1 up]";
sudo ifconfig wlan0 up
sleep 1
echo "[sudo ifconfig wlan2 up]";
sudo ifconfig wlan1 up
sleep 1
echo "[sudo ifconfig wlan3 up]";
sudo ifconfig wlan3 up
sleep 1
echo "[sudo ifconfig wlan4 up]";
sudo ifconfig wlan4 up
sleep 1

echo "[sudo ifconfig]";
sleep 1
sudo ifconfig
sleep 2
echo ""

echo "[sudo iwconfig]";
sleep 1
sudo iwconfig 
sleep 2

echo "Done.";

