#!/bin/bash
echo ""
echo "dropping caches.."
echo ""
echo "sync; echo 1 > /proc/sys/vm/drop_caches"
sudo sync; sudo echo 1 > /proc/sys/vm/drop_caches
echo ""
sleep 1
echo "Complete"
echo ""
sleep 1
echo "clear dentries and ..."
echo ""
echo "sync; echo 2 > /proc/sys/vm/drop_caches"
sudo sync; sudo echo 2 > /proc/sys/vm/drop_caches
echo ""
sleep 1
echo "Complete"
echo ""
sleep 1
echo "clear more shit.."
echo ""
echo "sync; echo 3 > /proc/sys/vm/drop_caches "
sudo sync; sudo echo 3 > /proc/sys/vm/drop_caches 
echo ""
echo "Complete"
echo ""
