#!/bin/bash
#Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1:37m"
ENDCOLOR="\033[0m"
alias ll='ls -Al'
clear
echo -e $CYAN"Change permissions script"$ENDCOLOR;
echo ""
echo -e $CYAN"Which folder do you want to start in? [/Users/...] "$ENDCOLOR;
read STARTFOLDER

echo ""
echo -e $BLUE"Changing directory to $STARTFOLDER.."$ENDCOLOR;
echo ""
cd $STARTFOLDER
pwd
echo ""
echo -e $CYAN"Which files and/or folders do you want to change? Separate multiple files and folders with a space. [folder1/ file1 folder2/ file2 ..] "$ENDCOLOR;
read SELECTED
echo ""

echo -e $CYAN"Change ownership to which group and user? [root:wheel] "$ENDCOLOR;
read NEWGRPUSR
echo ""
echo -e $BLUE"Selecting $NEWGRPUSR for $SELECTED in $STARTFOLDER." $ENDCOLOR;
echo ""
echo -e $YELLOW"Is this correct? "$ENDCOLOR;
read GO

if [[ $GO = 'y' || $GO = 'Y' || $GO = 'yes' || $GO = 'Yes' || $GO = 'YES' ]]; then
  
  echo ""
  echo -e $YELLOW"Excecuting command: sudo chown $NEWGRPUSR $SELECTED.."$ENDCOLOR;
  sleep 1
  echo ""
  sudo chown $NEWGRPUSR $SELECTED
  echo ""
  echo -e $GREEN"Complete."$ENDCOLOR;
  ls -Al

else

  echo ""
  echo -e $YELLOW"Exiting.."$ENDCOLOR;
  exit

fi
