#!/bin/bash
disk1="sda"
disk2="sdb"
echo "Select disk1 [default sda] ";
echo ""
echo "Seclect disk2 [default sdb] ";
echo ""
echo "Installing pv.."
echo ""
sudo apt-get install pv -y
echo ""
echo "Running [sudo pv < /dev/$disk1 > /dev/$disk2"
echo ""
sudo pv < /dev/$disk1 > /dev/$disk2
