#!/bin/bash
clear

## Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"


echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $BLUE"#                                  ||"$ENDCOLOR;
echo -e $BLUE"#                                  ||_________________________/'|"$ENDCOLOR;
echo -e $BLUE"#                                 _| O======/                   |"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+-+-+-+ +-+ +-+ +-+    |_|              ============  |"$ENDCOLOR;
echo -e $BLUE"# |f|u|c|k| |e|m| |.| |.| |.|     |  __   ______________________|"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+-+-+-+ +-+-+-+-+-+     |_/  )  (     |___||     O-   /"$ENDCOLOR;
echo -e $BLUE"# |T|A|K|E| |I|T| |A|L|L|!|            (  )    /  / |_________/"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+ +-+-+ +-+-+-+-+            (  )   /  /    | ) |   |"$ENDCOLOR;
echo -e $BLUE"#                                     (__)  /  /     \___|__("$ENDCOLOR;
echo -e $BLUE"#                                          /  / Katoolin:)   \ "$ENDCOLOR;
echo -e $BLUE"#                                         /  / Kali-Tools )   \ "$ENDCOLOR;
echo -e $BLUE"#                                        /  / for Ubuntu,  )___\ "$ENDCOLOR;
echo -e $BLUE"#                                       /  / Mint, and Debian"$ENDCOLOR;
echo -e $BLUE"#                                      /__/"$ENDCOLOR;
echo -e $BLUE"#                                "$ENDCOLOR;
echo ""

echo -e $YELLOW"Install Kali-Tools with Katoolin!"$ENDCOLOR
sleep 1
echo ""
cd ~/ 
echo -e $BLUE"Cloning katoolin repository .. "$ENDCOLOR;
sleep 0.5
git clone https://github.com/LionSec/katoolin.git
echo ""
sleep 1

echo -e $BLUE"Adding Katoolin to /usr/bin and setting as executable.."$ENDCOLOR;
echo ""
sudo cp katoolin/katoolin.py /usr/bin/katoolin
echo ""
sudo chmod +x /usr/bin/katoolin
echo ""
echo -e $GREEN"Katoolin Installed Successfully!"$ENDCOLOR;
echo ""

echo -e $YELLOW"To run Katoolin, simply type 'sudo katoolin'."$ENDCOLOR;
echo ""
sleep 1

echo -e $YELLOW"Run Katoolin Now? "$ENDCOLOR;

read RUNKATOOLIN

if [[ $RUNKATOOLIN = 'y' || $RUNKATOOLIN = 'Y' ]] ; then

	clear
	echo -e $BLUE"###############################################################"$ENDCOLOR;
	echo -e $YELLOW" __            __  .__                  .__                  "$ENDCOLOR;
	echo -e $YELLOW"|  | _______ _/  |_|  |__   ____   ____ |  |   ____   ____   "$ENDCOLOR;
	echo -e $YELLOW"|  |/ /\__  \\   __\  |  \ /  _ \ /  _ \|  |  /  _ \ /  _ \  "$ENDCOLOR;
	echo -e $YELLOW"|    <  / __ \|  | |   Y  (  <_> |  <_> )  |_(  <_> |  <_> ) "$ENDCOLOR;
	echo -e $YELLOW"|__|_ \(____  /__| |___|  /\____/ \____/|____/\____/ \____/  "$ENDCOLOR;
	echo -e $YELLOW"     \/     \/          \/                                   "$ENDCOLOR;
	echo -e $YELLOW"       Thank you for Pledging Your Soul to Kathooloo         "$ENDCOLOR;
	echo -e $BLUE"###############################################################"$ENDCOLOR;
	echo ""
	sleep 1
	sudo katoolin

else

	echo -e $BLUE"Okay. Maybe later."$ENDCOLOR;
	echo ""
	sleep 1

fi
