#!/bin/bash
clear

## Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"


echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $RED"#################################################################"$ENDCOLOR;
echo -e $BLUE"#                                 ||"$ENDCOLOR;
echo -e $BLUE"#                                 ||_________________________/'|"$ENDCOLOR;
echo -e $BLUE"#                                _| O======/                   |"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+-+-+-+ +-+ +-+ +-+   |_|              ============  |"$ENDCOLOR;
echo -e $BLUE"# |f|u|c|k| |e|m| |.| |.| |.|    |  __   ______________________|"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+-+-+-+ +-+-+-+-+-+    |_/  )  (     |___||     O-   /"$ENDCOLOR;
echo -e $BLUE"# |T|A|K|E| |I|T| |A|L|L|!|           (  )    /  / |_________/"$ENDCOLOR;
echo -e $BLUE"# +-+-+-+-+ +-+-+ +-+-+-+-+           (  )   /  /    | ) |   |"$ENDCOLOR;
echo -e $BLUE"#                                     (__)  /  /     \___|__("$ENDCOLOR;
echo -e $BLUE"#                                          /  /          )   \ "$ENDCOLOR;
echo -e $BLUE"#                                         /  /            )   \ "$ENDCOLOR;
echo -e $BLUE"#                                        /  /              )___\ "$ENDCOLOR;
echo -e $BLUE"#                                       /  / "$ENDCOLOR;
echo -e $BLUE"#                                      /__/"$ENDCOLOR;
echo -e $BLUE"#                                "$ENDCOLOR;
echo ""
echo -e $YELLOW"Setup Screenfetch"$ENDCOLOR
sleep 1
echo ""
sudo mkdir -p root/backup
cd root/backup

echo -e $YELLOW"Installing prerequisites.."$ENDCOLOR;
echo ""
sudo apt install bc scrot lsb-release -y
echo -e $BLUE"Complete."$ENDCOLOR;
echo ""

echo -e $BLUE"Cloning screenfetch repository .. "$ENDCOLOR;
sleep 0.5

if [[ -d "/root/backup/screenFetch" ]] ; then

	echo ""
	echo -e $BLUE"Directory already exists, so updating repository.."$ENDCOLOR;
	echo ""
	echo -e $BLUE"[cd /root/backup/screenFetch && sudo git pull]"$ENDCOLOR;
	echo ""
	cd /root/backup/screenFetch && sudo git pull
	echo -e $BLUE"Complete."$ENDCOLOR;
	echo ""
	
	sudo mkdir -p /usr/local/bin
	sudo cp /root/backup/screenFetch/screenfetch-dev /usr/local/bin/screenfetch
	echo ""
	sleep 0.5
	echo -e $YELLOW"Setting screenfetch as executable. Installing in /usr/bin.."$ENDCOLOR;
	sudo chmod +x /usr/local/bin/screenfetch
	echo ""

else 

	git clone https://github.com/KittyKatt/screenFetch.git
	echo ""
	sudo mkdir -p /usr/local/bin
	sudo cp screenFetch/screenfetch-dev /usr/local/bin/screenfetch
	echo ""
	sleep 0.5
	echo -e $YELLOW"Setting screenfetch as executable. Installing in /usr/bin.."$ENDCOLOR;
	sudo chmod +x /usr/local/bin/screenfetch
	echo ""

fi 

echo -e $GREEN"Screenfetch Setup Successfully!"$ENDCOLOR;
sleep 1
echo ""

echo -e $BLUE"###############################################################"$ENDCOLOR;
echo -e $YELLOW"                      Operation Complete                   "$ENDCOLOR;
echo -e $BLUE"###############################################################"$ENDCOLOR
exit 0

