#!/bin/bash
clear
#Colors

dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

echo -e $BLUE"#################################################################"$ENDCOLOR; 
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
echo ""
echo -e $YELLOW"Copy Configs"$ENDCOLOR
sleep 1
echo -e $YELLOW"Copy bashrc? [y/n] "$ENDCOLOR;
read COPYBASHRC

if [[ $COPYBASHRC = 'y' || $COPYBASHRC = 'Y' ]] ; then

echo -e $BLUE"Making a backup first. "$ENDCOLOR;
echo ""
sleep 1
echo cp ~/.bashrc ~/.bashrc.bak
sleep 1
echo ""
echo -e $BLUE"Copying.. "$ENDCOLOR;
echo ""
sleep 1
echo cp ../configs/bashrc ~/.bashrc
sleep 1
echo -e $GREEN"Bashrc copied successfully!"$ENDCOLOR;
echo ""
sleep 1
echo -e $YELLOW"Source bashrc now?"$ENDCOLOR;
read SOURCEBASHRC

if [[ $SOURCEBASHRC = 'y' || $SOURCEBASHRC = 'Y' ]] ; then

clear && source ~/.bashrc

else

echo -e $BLUE"Okay. Maybe later."$ENDCOLOR;
echo ""
sleep 1

fi

echo -e $YELLOW"Copy htoprc? "$ENDCOLOR;
read COPYHTOPRC

if [[ $COPYHTOPRC = 'y' || $COPYHTOPRC = 'Y' ]] ; then

echo -e $BLUE"Making a backup first."$ENDCOLOR;
echo ""
sleep 1
echo cp ~/.config/htop/htoprc ~/.config/htop/htoprc.bak
sleep 1
echo ""
echo -e $BLUE"Copying.."$ENDCOLOR;
echo ""
sleep 1
echo cp ../configs/htoprc ~/.config/htop/htoprc
sleep 1
echo -e $GREEN"Htoprc copied successfully!"$ENDCOLOR;
echo ""
sleep 1

else

echo -e $BLUE"Okay. Maybe some other time. "$ENDCOLOR;
sleep 1
fi
echo ""
echo -e $BLUE"###############################################################"$ENDCOLOR;
echo -e $YELLOW"                      Operation Complete                   "$ENDCOLOR;
echo -e $BLUE"###############################################################"$ENDCOLOR

